
public class Tools 
{
    
    
    /**Pauses the game thread for a certain amount of time
     * @param pause the amount of time in miliseconds to pause the game
     */
    public static void pause(int pause)
    {
        if(pause<0)
        {pause=0;}
        try
        {
            Thread.sleep(pause);
        }catch(InterruptedException ex){}
    }
    
    /**Generates a random number between 0 and n-1
     * @param n the max value to be generated by the method +1
     */
    public static int random(int n)
    {
        int num = (int)(Math.random()*n);
        return num;
    }
}
